rootfs/learning-center/src/XRayLP/LearningCenterBundle/Entity/File.php
<?php
/**
 * @link https://github.com/XRayLP/learning-center-bundle
 * @copyright Copyright (c) 2018 Niklas Loos <https://github.com/XRayLP>
 * @license GPL-3.0 <https://github.com/XRayLP/learning-center-bundle/blob/master/LICENSE>
 */

namespace App\XRayLP\LearningCenterBundle\Entity;

use Contao\StringUtil;
use Contao\System;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * File Entity
 *
 * @ORM\Entity(repositoryClass="App\XRayLP\LearningCenterBundle\Repository\FileRepository")
 * @ORM\Table(name="tl_files")
 * @package App\XRayLP\LearningCenterBundle\Entity
 */
class File
{


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", length=10)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $pid;

    /**
     * @ORM\Column(type="integer", length=10, options={"default":"0"})
     */
    private $tstamp = 0;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $uuid;

    /**
     * @ORM\Column(type="string", length=16, options={"default":""})
     */
    private $type = '';

    /**
     * @ORM\Column(type="string", length=1022, options={"default":""})
     */
    private $path = '';

    /**
     * @ORM\Column(type="string", length=16, options={"default":""})
     */
    private $extension = '';

    /**
     * @ORM\Column(type="string", length=32, options={"default":""})
     */
    private $hash = '';

    /**
     * @ORM\Column(type="string", length=1, options={"default":"1"})
     */
    private $found = 1;

    /**
     * @ORM\Column(type="string", length=255, options={"default":""})
     */
    private $name = '';

    /**
     * @ORM\Column(type="integer", length=11, options={"default":"0"})
     */
    private $importantPartX = 0;

    /**
     * @ORM\Column(type="integer", length=11, options={"default":"0"})
     */
    private $importantPartY = 0;

    /**
     * @ORM\Column(type="integer", length=11, options={"default":"0"})
     */
    private $importantPartWidth = 0;

    /**
     * @ORM\Column(type="integer", length=11, options={"default":"0"})
     */
    private $importantPartHeight = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $meta;

    /**
     * @ORM\Column(type="string", length=11, nullable=true)
     */
    private $shared_tstamp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $shared_groups;

    /**
     * @ORM\Column(type="string", length=1, options={"default":""})
     */
    private $shared = '';

    /**
     * @ORM\Column(type="integer", length=11, nullable=true)
     */
    private $owner;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * @param mixed $pid
     */
    public function setPid($pid)
    {
        $this->pid = $pid;
    }

    /**
     * @return mixed
     */
    public function getTstamp()
    {
        return $this->tstamp;
    }

    public function getDate()
    {
        return date('d. M Y', $this->tstamp);
    }

    /**
     * @param mixed $tstamp
     */
    public function setTstamp($tstamp)
    {
        $this->tstamp = $tstamp;
    }

    /**
     * @return mixed
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * @param mixed $uuid
     */
    public function setUuid($uuid)
    {
        $this->uuid = $uuid;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * @param mixed $path
     */
    public function setPath($path)
    {
        $this->path = $path;
    }

    /**
     * @return mixed
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * @param mixed $extension
     */
    public function setExtension($extension)
    {
        $this->extension = $extension;
    }

    /**
     * @return mixed
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * @param mixed $hash
     */
    public function setHash($hash)
    {
        $this->hash = $hash;
    }

    /**
     * @return mixed
     */
    public function getFound()
    {
        return $this->found;
    }

    /**
     * @param mixed $found
     */
    public function setFound($found)
    {
        $this->found = $found;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getImportantPartX()
    {
        return $this->importantPartX;
    }

    /**
     * @param mixed $importantPartX
     */
    public function setImportantPartX($importantPartX)
    {
        $this->importantPartX = $importantPartX;
    }

    /**
     * @return mixed
     */
    public function getImportantPartY()
    {
        return $this->importantPartY;
    }

    /**
     * @param mixed $importantPartY
     */
    public function setImportantPartY($importantPartY)
    {
        $this->importantPartY = $importantPartY;
    }

    /**
     * @return mixed
     */
    public function getImportantPartWidth()
    {
        return $this->importantPartWidth;
    }

    /**
     * @param mixed $importantPartWidth
     */
    public function setImportantPartWidth($importantPartWidth)
    {
        $this->importantPartWidth = $importantPartWidth;
    }

    /**
     * @return mixed
     */
    public function getImportantPartHeight()
    {
        return $this->importantPartHeight;
    }

    /**
     * @param mixed $importantPartHeight
     */
    public function setImportantPartHeight($importantPartHeight)
    {
        $this->importantPartHeight = $importantPartHeight;
    }

    /**
     * @return mixed
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * @param mixed $meta
     */
    public function setMeta($meta)
    {
        $this->meta = $meta;
    }

    /**
     * @return mixed
     */
    public function getSharedTstamp()
    {
        return $this->shared_tstamp;
    }

    public function getSharedDate()
    {
        return date('d. M Y', $this->shared_tstamp);
    }

    /**
     * @param mixed $shared_tstamp
     */
    public function setSharedTstamp($shared_tstamp)
    {
        $this->shared_tstamp = $shared_tstamp;
    }

    public function removeSharedGroup(MemberGroup $memberGroup)
    {
        $arrGroups = array();
        $collection = $this->getSharedGroups();
        $collection->removeElement($memberGroup);
        $arrCollection = $collection->toArray();

        foreach ($arrCollection as $memberGroup)
        {
            if ($memberGroup instanceof MemberGroup)
            {
                $arrGroups[] = $memberGroup->getId();
            }
        }
        $this->shared_groups = serialize($arrGroups);

        if (empty($arrGroups))
        {
            $this->setShared(false);
            $this->setSharedTstamp(null);
        }
    }

    public function addSharedGroup(MemberGroup $memberGroup)
    {
        $arrGroups = array();
        $collection = $this->getSharedGroups();
        $collection->add($memberGroup);
        $arrCollection = $collection->toArray();

        foreach ($arrCollection as $memberGroup)
        {
            if ($memberGroup instanceof MemberGroup)
            {
                $arrGroups[] = $memberGroup->getId();
            }
        }

        $this->shared_groups = serialize($arrGroups);

        if (count($arrGroups) === 1){
            $this->setShared(true);
            $this->setSharedTstamp(time());
        }
    }

    /**
     * @return ArrayCollection
     */
    public function getSharedGroups()
    {
        $arrGroups = StringUtil::deserialize($this->shared_groups);
        $groups = \System::getContainer()->get('doctrine')->getRepository(MemberGroup::class)->findBy(['id' => $arrGroups]);
        $collection = new ArrayCollection($groups);

        return $collection;
    }

    /**
     * @param mixed $groups
     */
    public function setSharedGroups($groups)
    {
        $this->shared_groups = $groups;
    }

    /**
     * @return mixed
     */
    public function getShared()
    {
        return $this->shared;
    }

    /**
     * @param mixed $shared
     */
    public function setShared($shared)
    {
        $this->shared = $shared;
    }

    /**
     * @return Member
     */
    public function getOwner(): Member
    {
        return System::getContainer()->get('doctrine')->getRepository(Member::class)->findOneById($this->owner);
    }

    /**
     * @param Member $owner
     */
    public function setOwner(Member $owner)
    {
        $this->owner = $owner->getId();
    }


}

rootfs/learning-center/src/XRayLP/LearningCenterBundle/Resources/views/modules/catalog_timeline.html.twig
{% extends '@LearningCenter/base.html.twig' %}

{% block main %}

    <div class="catalog-timeline">
    {% for file in files %}
        <div class="card text-center">
            <div class="card-header">{{ file.shared_group }}</div>
            <div class="card-body">
                <h5>{{ file.name }}</h5>

                <a class="btn btn-primary" href="{{ file.href }}"><i class="fas fa-download"></i><span>Download</span></a>
            </div>
            <div class="card-footer text-muted">
                {{ file.shared_time }}
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

rootfs/learning-center/src/XRayLP/LearningCenterBundle/Resources/views/modules/dashboard.html.twig
{% extends '@LearningCenter/base.html.twig' %}

{% block main %}
    <div class="dashboard">
        <div class="card">
            <div class="card-body">
                <h5>{% trans %}Welcome %name%, in the Learning Center of the School %schoolname%.{% endtrans %}</h5>
            </div>
        </div>
    </div>
{% endblock %}

rootfs/learning-center/src/XRayLP/LearningCenterBundle/Resources/views/modules/files.html-bu.twig
{% extends '@LearningCenter/base.html.twig' %}

{% block main %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            {% for item in breadcrumb %}
            <li class="breadcrumb-item active" aria-current="page"><a href="{{ item.href }}">{{ item.name }}</a></li>
            {% endfor %}
        </ol>
    </nav>

    {% if errors %}
        {% for error in errors %}
                <p class="error">{{ error }}</p>
        {% endfor %}
    {% endif %}

    {{ form_errors(upload) }}

    {{ test|raw }}

    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group">
            <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#files_upload_modal"><i class="fa fa-upload"></i><span>Upload</span></button>
            <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#files_folder_modal"><i class="fa fa-folder"></i><span>New Folder</span></button>
            <button type="button" class="btn btn-dark btn-download"><i class="fa fa-download"></i><span>Download</span></button>
            <button type="button" class="btn btn-primary btn-dark btn-delete" data-toggle="modal" data-target="#files_delete_modal"><i class="fa fa-trash"></i><span>Delete</span></button>
            <button type="button" class="btn btn-primary btn-dark btn-share" data-toggle="modal" data-target="#files_share_modal"><i class="fa fa-trash"></i><span>Share</span></button>
        </div>
    </div>
    {% if files %}
    <div class="row files">
        {% for file in files %}
        <div class="col-6 col-md-4 col-lg-3">
            <div class="icon">
                <input type="checkbox" name="checks-files" class="form-check-input {% if file.shared == 1 %} shared {% endif %}" id="{{ file.id }}" data-href="{{ file.href }}">

                {% if file.type == 'folder' %}
                    <a href="{{ file.href }}">
                    <i class="fa fa-folder fa-5x"></i>
                {% else %}
                    {% if file.extension == 'jpg' %}
                    <i class="fa fa-file-image fa-5x"></i>
                    {% elseif file.extension == 'docx' %}
                    <i class="fa fa-file-word fa-5x"></i>
                    {% elseif file.extension == 'pptx' %}
                    <i class="fa fa-file-powerpoint fa-5x"></i>
                    {% elseif file.extension == 'xlsx' %}
                    <i class="fa fa-file-excel fa-5x"></i>
                    {% elseif file.extension == 'pdf' %}
                    <i class="fa fa-file-pdf fa-5x"></i>
                    {% elseif file.extension == 'zip' %}
                    <i class="fa fa-file-archive fa-5x"></i>
                    {% elseif file.extension == 'mp4' %}
                    <i class="fa fa-file-video fa-5x"></i>
                    {% elseif file.extension == 'mp3' %}
                    <i class="fa fa-file-audio fa-5x"></i>
                    {% elseif file.extension == 'txt' %}
                    <i class="fa fa-file-text fa-5x"></i>
                    {% else %}
                    <i class="fa fa-file fa-5x"></i>
                    {% endif %}
                {% endif %}
                </a>
            </div>
            <span class="name" title="{{ file.name }}">{{ file.name }}</span><br>
            <span class="date">
                {% if file.shared == 1 %}
                <i class="fa fa-users"></i>
                {% endif %}
                {{ file.time }}
                </span>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="modals">
        <div class="modal fade" id="files_upload_modal" tabindex="-1" role="dialog">
            {{ form_start(upload) }}
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Upload</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ form_widget(upload.path) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        {{ form_widget(upload.submit) }}
                    </div>
                </div>
            </div>
            {{ form_end(upload) }}
        </div>

        <div class="modal fade" id="files_folder_modal" tabindex="-1" role="dialog">
            {{ form_start(folder) }}
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">New Folder</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ form_widget(folder.name) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        {{ form_widget(folder.submit) }}
                    </div>
                </div>
            </div>
            {{ form_end(folder) }}
        </div>

        <div class="modal fade" id="files_delete_modal" tabindex="-1" role="dialog">
            {{ form_start(delete) }}
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">New Folder</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Would your really like to delete this file?</p>
                        {{ form_widget(delete.id) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        {{ form_widget(delete.submit) }}
                    </div>
                </div>
            </div>
            {{ form_end(folder) }}
        </div>
        {% if isShare %}
        <div class="modal fade" id="files_share_modal" tabindex="-1" role="dialog">
            {{ form_start(share) }}
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Share File</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Would your really like to share this file?</p>
                        {{ form_widget(share.id) }}
                        {{ form_widget(share.sharedGroups) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        {{ form_widget(share.submit) }}
                    </div>
                </div>
            </div>
            {{ form_end(share) }}
        </div>
        {% endif %}
    </div>
{% endblock %}

rootfs/learning-center/src/XRayLP/LearningCenterBundle/Resources/views/modules/files.html.twig
{% extends '@LearningCenter/base.html.twig' %}

{% block javascripts %}
    <script>
        $(document).ready(function () {
            Dropzone.options.dropzoneForm = {
                maxFiles: 1,
                dictMaxFilesExceeded: 'Only 1 Image can be uploaded',
                maxFilesize: 3,  // in Mb
                addRemoveLinks: true,
                init: function () {
                    this.on("maxfilesexceeded", function(file) {
                        this.removeFile(file);
                    });
                    this.on("sending", function(file, xhr, formData) {
                        // send additional data with the file as POST data if needed.
                        // formData.append("key", "value");
                    });
                    this.on("success", function(file, response) {
                        /*var files = ;
                        $('.files').html(' ');
                        $('.files').append(files);*/
                    });
            }}
        });

    </script>

    <script>
        $(document).ready(function () {
            var $groupType = $('#groupType');
            // When sport gets selected ...
            $groupType.change(function () {
                // ... retrieve the corresponding form.
                var $form = $(this).closest('form');
                // Simulate form data, but only include the selected sport value.
                var data = {};
                data[$groupType.attr('name')] = $groupType.val();
                // Submit data via AJAX to the form's action path.
                $.ajax({
                    url: '{{ url('learningcenter_files') }}',
                    type: $form.attr('method'),
                    data: data,
                    success: function (html) {
                        // Replace current position field ...
                        $('#memberGroups').replaceWith(
                            // ... with the returned one from the AJAX response.
                            $(html).find('#memberGroups')
                        );
                        // Position field now displays the appropriate positions.
                    }
                });
            });
        });
    </script>
{% endblock %}

{% block main %}
    {{ include('@LearningCenter/modules/filemanager/filemanager.html.twig', {'files': files, 'breadcrumb': breadcrumb, 'usedSpace': usedSpace, 'upload': upload, 'create_directory': create_directory, 'download': download, 'delete': delete, 'share': share, 'share_edit': share_edit}) }}
{% endblock %}

rootfs/learning-center/src/XRayLP/LearningCenterBundle/Resources/views/modules/project_create.html.twig
{% extends '@LearningCenter/base.html.twig' %}

{% block main %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

rootfs/learning-center/src/XRayLP/LearningCenterBundle/Resources/views/modules/project_list.html.twig
{% extends '@LearningCenter/base.html.twig' %}
{% trans_default_domain 'project' %}

{% block main %}
    {% if is_granted('project.create') %}
    <a class="btn btn-outline-primary" href="{{ url('lc_projects_create') }}">{% trans %}project.create{% endtrans %}</a>
    {% endif %}
    {% if showProjects %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">{% trans %}project.state{% endtrans %}</th>
                <th scope="col">{% trans %}project.name{% endtrans %}</th>
                <th scope="col">{% trans %}project.description{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
            {% for project in projects %}
                <tr>
                    <td>
                        {% if project.confirmed %}
                            <i class="fas fa-check-circle mr-1 text-success" data-toggle="tooltip" data-placement="top" title="The project has to be confirmed by a teacher!"></i>
                        {% else %}
                            <i class="fas fa-clock mr-1 text-danger" data-toggle="tooltip" data-placement="top" title="Project is confirmed by a teacher!"></i>
                        {% endif %}
                    </td>
                    <td><a href="{{ url('lc_projects_detail', {'id': project.id })}}">{{ project.name }}</a></td>
                    <td>{{ project.description }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}

    {% if is_granted('project.list.all') %}
        <a class="btn btn-outline-secondary" href="">{% trans %}project.list.all{% endtrans %}</a>
    {% endif %}
{% endblock %}

rootfs/learning-center/src/XRayLP/LearningCenterBundle/Resources/views/modules/user_details.html.twig
{% extends '@LearningCenter/base.html.twig' %}

{% block main %}
    <h1 class="display-3">{{ member.username }}</h1>
    <img src="{{ member.avatar }}" alt="{{ member.username }}" class="rounded-circle border-dark" width="250">
    <div class="details">
        <dl class="row">
            <dt class="col-sm-3">Vorname</dt>
            <dd class="col-sm-9">{{ member.firstname }}</dd>

            <dt class="col-sm-3">Nachname</dt>
            <dd class="col-sm-9">{{ member.lastname }}</dd>

            <dt class="col-sm-3">E-Mail</dt>
            <dd class="col-sm-9">{{ member.email }}</dd>

            <dt class="col-sm-3">Geschlecht</dt>
            <dd class="col-sm-9">{{ member.gender }}</dd>
        </dl>
    </div>
{% endblock %}

rootfs/learning-center/src/XRayLP/LearningCenterBundle/Resources/views/modules/user_list.html.twig
{% extends '@LearningCenter/base.html.twig' %}

{% block main %}
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Profilbild</th>
            <th scope="col">Vorname</th>
            <th scope="col">Nachname</th>
        </tr>
        </thead>
        <tbody>
        {% for user in members %}
            <tr class="clickable-row" data-href="{{ user.url }}">
                <td><img src="{{ user.avatar }}" width="36" height="36" style="border-radius: 100%" /></td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.lastname }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}